name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup dependencies
        run: |
          sudo apt-get install libtiff5 imagemagick tidy xmllint xmlstarlet

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 10.22.0

      - name: Generate Files
        run: |
          ./scripts/setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.74.3'
          extended: true
      - name: Build Hugo site
        run: hugo

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
