name: Publish on GitHub pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Setup dependencies
        run: |
          sudo apt-get install libtiff5 imagemagick tidy libxml2-utils xmlstarlet

      - name: Setup Node.js
        uses: actions/setup-node@v3.5.1
        with:
          node-version-file: '.nvmrc'

      - name: Generate Files
        run: |
          ./scripts/setup.sh

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.104.3'
          extended: true

      - name: Build Hugo site
        run: hugo

      - name: Puppeteer
        run: |
          ./themes/projektemacher-base/scripts/init/package.json.sh
          ./themes/projektemacher-base/scripts/github/check-js-errors.sh

      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
